### ISSUE TITLE
Based on GIMP?

### ISSUE THREAD

**Issue by eniocc** [SEPAEL/Peritus#2]
Hello, after few uses I noticed that program is very similar to GIMP.
Did you are based on GIMP source code?

Thanks.

**Comment by eniocc** [comment]
I just find out it "The software is created in C++ utilizing the QT Framework for cross-platform and graphical user interface support. It combines the OpenCV library for image processing with the FFmpeg multimedia package. DocxFactory, used to generate report draughts in [MS](https://www.sciencedirect.com/topics/medicine-and-dentistry/multiple-sclerosis) Word-compatible format, is the lone exception, as it is only compatible with the Windows operating system." in that paper [here](https://doi.org/10.1016/j.fsisyn.2022.100313). 

It's right? Any other important information to cite? 
Thanks.

**Comment by SEPAEL** [comment]
The information you've listed is accurate. For more in-depth details, you can refer to the following article: "[Peritus Framework: Towards multimedia evidence analysis uniformization in brazilian distributed forensic model](https://www.sciencedirect.com/science/article/pii/S2666281720303917)".

**Comment by eniocc** [comment]
Thank you so much sir.
